Лабораторная работа 5
$$ \text{Хачатрян Армен БПМ153} $$
$$ \text{Вариант 28} $$
$$ \text{5.1.28 }$$
$$ A =  \begin{pmatrix}
  2.97& 0.4& 0.3& 1.98& 0& 0.1\\
  0.99& 4.9& 0.4& 2.97& 0.2& -0.3\\
  0& -1.8& 6.6& 3.3& 0.6& 0.8\\
  4.95& 1.6& 1.2& 8.91& 0.8& 0.3\\
  1.98& -1.5& 0.4& -1.98& 6.1& 0\\
  9.9& 1.4& 2.4& 5.94& 3.2& 23.3\\
\end{pmatrix}  $$   
$$ b =  \begin{pmatrix}
  -10.45\\ -8.28\\ 4.48\\ -26.93\\ 11.82\\ 38.84\\\end{pmatrix}$$

![%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202018-06-11%20%D0%B2%2012.41.27.png](attachment:%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202018-06-11%20%D0%B2%2012.41.27.png)

# ТЕОРИЯ

## Метод Гаусса

$$ A\overline{x}=\overline{b} $$

$$ \overline{x} = (x_1,\ldots,x_m)^T $$
$$ \overline{b} = (b_1,\ldots,b_m)^T $$
$$ A =  \begin{pmatrix}
  a_11& a_12& \ldots& a_1m\\
  a_21& a_22& \ldots& a_2m\\
  \ldots& \ldots& \ldots& \ldots\\
  a_m1& a_m2& \ldots& a_mm
\end{pmatrix}  $$
### Прямой ход
Состоит из m-1 шагов исключения
$$ \textbf{Первый шаг: } \text{исключение }  x_1 \text{ из уравнений с номерами i = 2,3,...,m} $$
$$ a_{11} \neq 0,  \mu_{i1} = {a_{i1}\over{a_{11}}}, i = 2,3,...,m, \mu_{i1} \text{ - множитель первого шага} $$
$$ a_{ij}^{(1)} = a_{ij} - \mu_{i1}a_{1j} $$
$$ b_{i}^{(1)} = b_{i} - \mu_{i1}b_{1} $$
$$ i,j = 2,3,...,m $$
$$ \textbf{Второй шаг: } \text{исключение }  x_2 \text{ из уравнений с номерами i = 3,4,...,m} $$
$$ a_{22}^{(1)} \neq 0,  \mu_{i2} = {a_{i2}^{(1)}\over{a_{22}^{(1)}}}, i = 3,4,...,m, \mu_{i2} \text{ - множитель второго шага} $$
$$ a_{ij}^{(2)} = a_{ij}^{(1)} - \mu_{i2}a_{2j}^{(1)} $$
$$ b_{i}^{(2)} = b_{i}^{(1)} - \mu_{i2}b_{2}^{(1)} $$
$$ i,j = 3,4,...,m $$
$$ \textbf{K-ый шаг: } $$ 
$$ a_{kk}^{(k-1)} \neq 0 \mu_{i2} = {a_{ik}^{(k-1)}\over{a_{kk}^{(k-1)}}}, i = k+1,...,m$$
### Обратный ход
$$x_m = {{b_{m}^{m-1}}\over{a_{mm}^{m-1}}} $$
$$ x_k = (b_{k}^{(k-1)} - a_{k,k+1}^{(k-1)}x_{k+1} - \ldots - a_{k,m}^{(k-1)}x_{m}){{1}\over{a_{kk}^{(k-1)}}}$$
$$ k = m-1,\ldots,1 $$

## Метод Зейделя

$$ x_1^{(k+1)} = 0+b_{12}x_2^{(k)}+b_{13}x_3^{(k)}+\ldots+b_{1m}x_m^{(k)}+c_1 $$
$$ x_2^{(k+1)} = b_{21}x_1^{(k+1)}+0+b_{23}x_3^{(k)}+\ldots+b_{2m}x_m^{(k)}+c_2 $$
$$\ldots$$
$$ x_m^{(k+1)} = b_{m1}x_1^{(k+1)}+b_{m2}x_2^{(k+1)}+\ldots+c_m $$
$$B=B_1+B_2, $$
$$\text{ где } {B_1} \text{ - нижняя треугольная матрица, а } {B_2} \text{ - верхняя треугольная матрица}$$
$$\overline{x}^{(k+1)} = B_1\overline{x}^{(k+1)}+B_2\overline{x}^{(k)}+\overline{c}$$
$$\textbf{Теорема 1: }{||B||<1 (||B||_1 \text{ или }||B||_{\infty})} $$
$$ \text{Тогда при любом } {\overline{x}^{(0)}} \text{ метод Зейделя сходится со скоростью геометрической прогрессии, } {q\leq||B||}$$
$$\textbf{Теорема 2: } \text{Пусть } {||B_1||+||B_2||<1}$$
$$\text{Тогда для любого } {\overline{x}^{(0)}} \text{ метод сходится и } {||\overline{x}^{(n)} - \overline{x}||\leq q^n||\overline{x}^{(0)}-\overline{x}||} \text{ , где } {q = {{||B_2||}\over{1-||B_1||}}} $$
$$\text{Критерий окончания: } {||\overline{x}^{(n)}-\overline{x}^{(n-1)}||<{{1-||B||}\over {B_2}}\varepsilon}$$

Начало

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

#### Задание 1

In [ ]:
A = np.array([[2.97,0.4,0.3,1.98,0,0.1],[0.99,4.9,0.4,2.97,0.2,-0.3],[0,-1.8,6.6,3.3,0.6,0.8],[4.95,1.6,1.2,8.91,0.8,0.3],[1.98,-1.5,0.4,-1.98,6.1,0],[9.9,1.4,2.4,5.94,3.2,23.3]])
A

array([[  2.97,   0.4 ,   0.3 ,   1.98,   0.  ,   0.1 ],
       [  0.99,   4.9 ,   0.4 ,   2.97,   0.2 ,  -0.3 ],
       [  0.  ,  -1.8 ,   6.6 ,   3.3 ,   0.6 ,   0.8 ],
       [  4.95,   1.6 ,   1.2 ,   8.91,   0.8 ,   0.3 ],
       [  1.98,  -1.5 ,   0.4 ,  -1.98,   6.1 ,   0.  ],
       [  9.9 ,   1.4 ,   2.4 ,   5.94,   3.2 ,  23.3 ]])

In [ ]:
b = np.array([-10.45,-8.28,4.48,-26.93,11.82,38.84])
b

array([-10.45,  -8.28,   4.48, -26.93,  11.82,  38.84])

In [ ]:
x = np.linalg.solve(A,b)
x

array([-2.28282828,  0.1       ,  1.3       , -2.21212121,  1.9       ,
        2.8       ])

In [ ]:
def Zeid_10(A, b, x_0):
    # приведение системы к удобному виду
    # пустые списки B1,B2 и c
    B1 = np.zeros((A.shape[0],A.shape[0]),dtype=np.float)
    B2 = np.zeros((A.shape[0],A.shape[0]),dtype=np.float)
    c = np.zeros(b.shape[0],dtype=np.float)
    # инициализируем B1, B2, c
    for i in range(B1.shape[0]):
        c[i]=b[i]/A[i,i]
        for j in range(B1.shape[0]):
            if i > j:
                B1[i,j] = -(A[i,j])/(A[i,i])
            elif i < j:
                B2[i,j] = -(A[i,j])/(A[i,i])
                
    # Проверка нормы B = B1+B2
    if np.linalg.norm(B1+B2,np.inf) >=1:
        print('Does not converge, norm of B = ', np.linalg.norm(B1+B2,np.inf))
        return np.linalg.norm(B1+B2,np.inf)
    print('Norm of B =',np.linalg.norm(B1+B2,np.inf))
    
    # непосредственно метод Зейделя

    x_k = x_0
    x_k_1 = x_0
    
    for _ in range(10):
        x_k = np.matmul(B1,x_k)+np.matmul(B2,x_k_1)+c
        x_k_1=x_k

    return x_k 
    
    

In [ ]:
x_10=Zeid_10(A, b, np.array([1,1,1,1,1,1]))
x_10

Norm of B = 0.993265993266


array([-1.90902895,  0.43866009,  1.43984244, -1.85189854,  1.82009872,
        3.13479167])

In [ ]:
print('Абсолютная погрешность решения x_10:', np.linalg.norm(x-x_10,np.inf))
print('Истинное решение:', x)
print('Приближенное решение:',x_10)

Абсолютная погрешность решения x_10: 0.373799333672
Истинное решение: [-2.28282828  0.1         1.3        -2.21212121  1.9         2.8       ]
Приближенное решение: [-1.90902895  0.43866009  1.43984244 -1.85189854  1.82009872  3.13479167]


In [ ]:
x_10=Zeid_10(A, b, np.array([100,-20,40,80,50,-10]))
x_10

Norm of B = 0.993265993266


array([  9.76660395,  11.00845507,   5.90707503,   9.2198233 ,
        -0.74354991,  13.50151144])

In [ ]:
print('Абсолютная погрешность решения x_10:', np.linalg.norm(x-x_10,np.inf))
print('Истинное решение:', x)
print('Приближенное решение:',x_10)

Абсолютная погрешность решения x_10: 12.0494322278
Истинное решение: [-2.28282828  0.1         1.3        -2.21212121  1.9         2.8       ]
Приближенное решение: [  9.76660395  11.00845507   5.90707503   9.2198233   -0.74354991
  13.50151144]


В первом случае взяли начальное приближение очень близко к корню, поэтому абсолютная погрешность значительно ниже, чем во втором случае.

### Задание 2

In [ ]:
def Zeid(A, b, x_0, eps):
    # приведение системы к удобному виду
    # пустые списки B и c
    B1 = np.zeros((A.shape[0],A.shape[0]),dtype=np.float)
    B2 = np.zeros((A.shape[0],A.shape[0]),dtype=np.float)
    c = np.zeros(b.shape[0],dtype=np.float)
    # инициализируем B1, B2, c
    for i in range(B1.shape[0]):
        c[i]=b[i]/A[i,i]
        for j in range(B1.shape[0]):
            if i > j:
                B1[i,j] = -(A[i,j])/(A[i,i])
            elif i < j:
                B2[i,j] = -(A[i,j])/(A[i,i])
                
    # проверка нормы B
    if np.linalg.norm(B1+B2,np.inf) >=1:
        print('Does not converge')
        return np.linalg.norm(B1+B2,np.inf)
    
    # непосредественно метод Зейделя

    x_k = x_0
    x_k_1 = x_0
    
    x_k = np.matmul(B1,x_k)+np.matmul(B2,x_k_1)+c
    k = 1
    w = ((1-np.linalg.norm(B1+B2,np.inf))/(np.linalg.norm(B2,np.inf)))*eps
    while np.linalg.norm(x_k-x_k_1,np.inf)>=w:
        x_k_1=x_k
        x_k = np.matmul(B1,x_k)+np.matmul(B2,x_k_1)+c
        k=k+1
    return x_k, k-1
    

In [ ]:
x0=np.random.randint(-100,100,6)
x0

array([-44, -75, -60,  64,  22, -97])

In [ ]:
print('Converges to', Zeid(A, b, x0, 10**(-6))[0], 'in',Zeid(A, b, x0, 10**(-6))[1], 'steps')

Converges to [-2.28282828  0.1         1.3        -2.21212121  1.9         2.8       ] in 108 steps


In [ ]:
x_n = Zeid(A, b, x0, 10**(-6))[0]

In [ ]:
print('Абсолютная погрешность решения x_n:', np.linalg.norm(x-x_n,np.inf))
print('Истинное решение:', x)
print('Приближенное решение:',x_n)

Абсолютная погрешность решения x_n: 2.99749958188e-09
Истинное решение: [-2.28282828  0.1         1.3        -2.21212121  1.9         2.8       ]
Приближенное решение: [-2.28282828  0.1         1.3        -2.21212121  1.9         2.8       ]


In [ ]:
Zeid(A, b, x0, 10**(-6))[1]

108

$$ \text{Конец}$$